# Generated by Django 4.0.2 on 2022-04-03 02:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Описание')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram id')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, default='', max_length=32, verbose_name='Юзернейм')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Баланс')),
                ('language_code', models.CharField(blank=True, max_length=8, verbose_name='Код языка')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Почта')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.tguser', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('status', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение в тех. поддержку',
                'verbose_name_plural': 'Обращения в тех. поддержку',
            },
        ),
    ]
