# Generated by Django 4.0.2 on 2022-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_purchase_options_tguser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products', verbose_name='Картинка'),
        ),
    ]
