# Generated by Django 4.0.2 on 2022-02-27 04:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='language_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Код языка'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Юзернейм'),
        ),
    ]
