# Generated by Django 4.0.2 on 2022-02-27 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_tguser_email_alter_tguser_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Почта'),
        ),
    ]
