# Generated by Django 4.0.2 on 2022-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_tguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Баланс'),
        ),
    ]
